# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 215c2a42662a21b41a40f8cd0046b103da0af8fadda447e65f86bba1222ece8e69b3c686705cdf6c703c1177f53551b71e0be1e8dc36c49772215c84853fb6ec

test:
  secret_key_base: cc9a5226d261c3f74ebfefd878c78661796d5a517f9f63531b6a84d84d1c36ea048cea999dc1f44bb7e1a3640ee9487070ebb0af1d98a333baad0ae1f2469bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
